//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHelperApp
{
    public partial class Member
    {
        protected global::System.Web.UI.WebControls.Label lblUsername;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Label lblMemberCookieStatus;
        protected global::System.Web.UI.WebControls.Label lblSessionInfo;
        protected global::System.Web.UI.WebControls.Label lblSessionId;
    }
}
