//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHelperApp
{
    public partial class Staff
    {
        protected global::System.Web.UI.WebControls.Label lblStaffName;
        protected global::System.Web.UI.WebControls.Label lblStaffSession;
        protected global::System.Web.UI.WebControls.Label lblSessionId;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.GridView gvMembers;
    }
}
