//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHelperApp.UnitConverterServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://studenthelperapp.local/", ConfigurationName="UnitConverterServiceRef.IUnitConverterService")]
    public interface IUnitConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://studenthelperapp.local/IUnitConverterService/ConvertUnits", ReplyAction="http://studenthelperapp.local/IUnitConverterService/ConvertUnitsResponse")]
        double ConvertUnits(double value, string fromUnit, string toUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://studenthelperapp.local/IUnitConverterService/ConvertUnits", ReplyAction="http://studenthelperapp.local/IUnitConverterService/ConvertUnitsResponse")]
        System.Threading.Tasks.Task<double> ConvertUnitsAsync(double value, string fromUnit, string toUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://studenthelperapp.local/IUnitConverterService/GetSupportedUnits", ReplyAction="http://studenthelperapp.local/IUnitConverterService/GetSupportedUnitsResponse")]
        string GetSupportedUnits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://studenthelperapp.local/IUnitConverterService/GetSupportedUnits", ReplyAction="http://studenthelperapp.local/IUnitConverterService/GetSupportedUnitsResponse")]
        System.Threading.Tasks.Task<string> GetSupportedUnitsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://studenthelperapp.local/IUnitConverterService/HealthCheck", ReplyAction="http://studenthelperapp.local/IUnitConverterService/HealthCheckResponse")]
        string HealthCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://studenthelperapp.local/IUnitConverterService/HealthCheck", ReplyAction="http://studenthelperapp.local/IUnitConverterService/HealthCheckResponse")]
        System.Threading.Tasks.Task<string> HealthCheckAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnitConverterServiceChannel : StudentHelperApp.UnitConverterServiceRef.IUnitConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnitConverterServiceClient : System.ServiceModel.ClientBase<StudentHelperApp.UnitConverterServiceRef.IUnitConverterService>, StudentHelperApp.UnitConverterServiceRef.IUnitConverterService {
        
        public UnitConverterServiceClient() {
        }
        
        public UnitConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnitConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnitConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnitConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConvertUnits(double value, string fromUnit, string toUnit) {
            return base.Channel.ConvertUnits(value, fromUnit, toUnit);
        }
        
        public System.Threading.Tasks.Task<double> ConvertUnitsAsync(double value, string fromUnit, string toUnit) {
            return base.Channel.ConvertUnitsAsync(value, fromUnit, toUnit);
        }
        
        public string GetSupportedUnits() {
            return base.Channel.GetSupportedUnits();
        }
        
        public System.Threading.Tasks.Task<string> GetSupportedUnitsAsync() {
            return base.Channel.GetSupportedUnitsAsync();
        }
        
        public string HealthCheck() {
            return base.Channel.HealthCheck();
        }
        
        public System.Threading.Tasks.Task<string> HealthCheckAsync() {
            return base.Channel.HealthCheckAsync();
        }
    }
}
